# Generated by Django 3.1.7 on 2021-03-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210328_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
        migrations.AddField(
            model_name='image',
            name='image_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.profile'),
        ),
    ]
