# Generated by Django 3.1.7 on 2021-03-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210328_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_profile',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
    ]
