# Generated by Django 2.2 on 2021-03-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_updateprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updateprofile',
            options={'ordering': ['first_name']},
        ),
    ]
