# Generated by Django 2.2 on 2021-03-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210330_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/photo.jpg', null=True, upload_to='profile/'),
        ),
    ]
