# Generated by Django 2.2 on 2021-03-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='post_likes', to='posts.IpModel'),
        ),
    ]
