# Generated by Django 2.2 on 2021-03-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20210331_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comment',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
