# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-31 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20210331_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
