# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-02 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20210402_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ManyToManyField(null=True, to='posts.Profile'),
        ),
        migrations.AlterField(
            model_name='updateprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
