# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-04 10:17
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20210402_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='pic'),
        ),
    ]
