# Generated by Django 2.2 on 2021-04-04 20:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_auto_20210404_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateProfile',
        ),
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='pic'),
        ),
    ]
